//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P6SOAP_AuthenticationService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/IntegrationFaultType/V1")]
    public partial class IntegrationFaultType
    {
        
        private IntegrationFaultCodeType errorTypeField;
        
        private int errorCodeField;
        
        private string errorDescriptionField;
        
        private string stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IntegrationFaultCodeType ErrorType
        {
            get
            {
                return this.errorTypeField;
            }
            set
            {
                this.errorTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorDescription
        {
            get
            {
                return this.errorDescriptionField;
            }
            set
            {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string StackTrace
        {
            get
            {
                return this.stackTraceField;
            }
            set
            {
                this.stackTraceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/IntegrationFaultType/V1")]
    public enum IntegrationFaultCodeType
    {
        
        /// <remarks/>
        General,
        
        /// <remarks/>
        Presentation,
        
        /// <remarks/>
        Network,
        
        /// <remarks/>
        Server,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Business Rules")]
        BusinessRules,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", ConfigurationName="P6SOAP_AuthenticationService.AuthenticationServicePortType")]
    public interface AuthenticationServicePortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Login", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(P6SOAP_AuthenticationService.IntegrationFaultType), Action="urn:Login", Name="IntegrationFault", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/IntegrationFaultType/V1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<P6SOAP_AuthenticationService.LoginResponse1> LoginAsync(P6SOAP_AuthenticationService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<P6SOAP_AuthenticationService.LogoutResponse1> LogoutAsync(P6SOAP_AuthenticationService.LogoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ReadDatabaseInstances", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(P6SOAP_AuthenticationService.IntegrationFaultType), Action="urn:ReadDatabaseInstances", Name="IntegrationFault", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/IntegrationFaultType/V1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<P6SOAP_AuthenticationService.ReadDatabaseInstancesResponse> ReadDatabaseInstancesAsync(P6SOAP_AuthenticationService.ReadDatabaseInstancesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ReadSessionProperties", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(P6SOAP_AuthenticationService.IntegrationFaultType), Action="urn:ReadSessionProperties", Name="IntegrationFault", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/IntegrationFaultType/V1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<P6SOAP_AuthenticationService.ReadSessionPropertiesResponse1> ReadSessionPropertiesAsync(P6SOAP_AuthenticationService.ReadSessionPropertiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:UpdateSessionProperties", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<P6SOAP_AuthenticationService.UpdateSessionPropertiesResponse1> UpdateSessionPropertiesAsync(P6SOAP_AuthenticationService.UpdateSessionPropertiesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")]
    public partial class Login
    {
        
        private string userNameField;
        
        private string passwordField;
        
        private int databaseInstanceIdField;
        
        private bool databaseInstanceIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int DatabaseInstanceId
        {
            get
            {
                return this.databaseInstanceIdField;
            }
            set
            {
                this.databaseInstanceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatabaseInstanceIdSpecified
        {
            get
            {
                return this.databaseInstanceIdFieldSpecified;
            }
            set
            {
                this.databaseInstanceIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")]
    public partial class LoginResponse
    {
        
        private bool returnField;
        
        private bool returnFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReturnSpecified
        {
            get
            {
                return this.returnFieldSpecified;
            }
            set
            {
                this.returnFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", Order=0)]
        public P6SOAP_AuthenticationService.Login Login;
        
        public LoginRequest()
        {
        }
        
        public LoginRequest(P6SOAP_AuthenticationService.Login Login)
        {
            this.Login = Login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", Order=0)]
        public P6SOAP_AuthenticationService.LoginResponse LoginResponse;
        
        public LoginResponse1()
        {
        }
        
        public LoginResponse1(P6SOAP_AuthenticationService.LoginResponse LoginResponse)
        {
            this.LoginResponse = LoginResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")]
    public partial class LogoutResponse
    {
        
        private bool returnField;
        
        private bool returnFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReturnSpecified
        {
            get
            {
                return this.returnFieldSpecified;
            }
            set
            {
                this.returnFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", Order=0)]
        public object Logout;
        
        public LogoutRequest()
        {
        }
        
        public LogoutRequest(object Logout)
        {
            this.Logout = Logout;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", Order=0)]
        public P6SOAP_AuthenticationService.LogoutResponse LogoutResponse;
        
        public LogoutResponse1()
        {
        }
        
        public LogoutResponse1(P6SOAP_AuthenticationService.LogoutResponse LogoutResponse)
        {
            this.LogoutResponse = LogoutResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")]
    public partial class ReadDatabaseInstancesResponseDatabaseInstance
    {
        
        private int databaseInstanceIdField;
        
        private string databaseEncodingField;
        
        private string databaseNameField;
        
        private DatabaseTypeType databaseTypeField;
        
        private string databaseUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int DatabaseInstanceId
        {
            get
            {
                return this.databaseInstanceIdField;
            }
            set
            {
                this.databaseInstanceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DatabaseEncoding
        {
            get
            {
                return this.databaseEncodingField;
            }
            set
            {
                this.databaseEncodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DatabaseName
        {
            get
            {
                return this.databaseNameField;
            }
            set
            {
                this.databaseNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DatabaseTypeType DatabaseType
        {
            get
            {
                return this.databaseTypeField;
            }
            set
            {
                this.databaseTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DatabaseUrl
        {
            get
            {
                return this.databaseUrlField;
            }
            set
            {
                this.databaseUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")]
    public enum DatabaseTypeType
    {
        
        /// <remarks/>
        Oracle,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SQL Server")]
        SQLServer,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadDatabaseInstancesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", Order=0)]
        public object ReadDatabaseInstances;
        
        public ReadDatabaseInstancesRequest()
        {
        }
        
        public ReadDatabaseInstancesRequest(object ReadDatabaseInstances)
        {
            this.ReadDatabaseInstances = ReadDatabaseInstances;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadDatabaseInstancesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadDatabaseInstancesResponse", Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DatabaseInstance", IsNullable=false)]
        public P6SOAP_AuthenticationService.ReadDatabaseInstancesResponseDatabaseInstance[] ReadDatabaseInstancesResponse1;
        
        public ReadDatabaseInstancesResponse()
        {
        }
        
        public ReadDatabaseInstancesResponse(P6SOAP_AuthenticationService.ReadDatabaseInstancesResponseDatabaseInstance[] ReadDatabaseInstancesResponse1)
        {
            this.ReadDatabaseInstancesResponse1 = ReadDatabaseInstancesResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")]
    public partial class ReadSessionPropertiesResponse
    {
        
        private bool isValidField;
        
        private int userObjectIdField;
        
        private string userNameField;
        
        private int databaseInstanceIdField;
        
        private string databaseEncodingField;
        
        private string databaseNameField;
        
        private DatabaseTypeType databaseTypeField;
        
        private string databaseUrlField;
        
        private bool ignoreNullComplexFieldsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsValid
        {
            get
            {
                return this.isValidField;
            }
            set
            {
                this.isValidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int UserObjectId
        {
            get
            {
                return this.userObjectIdField;
            }
            set
            {
                this.userObjectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int DatabaseInstanceId
        {
            get
            {
                return this.databaseInstanceIdField;
            }
            set
            {
                this.databaseInstanceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DatabaseEncoding
        {
            get
            {
                return this.databaseEncodingField;
            }
            set
            {
                this.databaseEncodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DatabaseName
        {
            get
            {
                return this.databaseNameField;
            }
            set
            {
                this.databaseNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public DatabaseTypeType DatabaseType
        {
            get
            {
                return this.databaseTypeField;
            }
            set
            {
                this.databaseTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DatabaseUrl
        {
            get
            {
                return this.databaseUrlField;
            }
            set
            {
                this.databaseUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool IgnoreNullComplexFields
        {
            get
            {
                return this.ignoreNullComplexFieldsField;
            }
            set
            {
                this.ignoreNullComplexFieldsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadSessionPropertiesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", Order=0)]
        public object ReadSessionProperties;
        
        public ReadSessionPropertiesRequest()
        {
        }
        
        public ReadSessionPropertiesRequest(object ReadSessionProperties)
        {
            this.ReadSessionProperties = ReadSessionProperties;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadSessionPropertiesResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", Order=0)]
        public P6SOAP_AuthenticationService.ReadSessionPropertiesResponse ReadSessionPropertiesResponse;
        
        public ReadSessionPropertiesResponse1()
        {
        }
        
        public ReadSessionPropertiesResponse1(P6SOAP_AuthenticationService.ReadSessionPropertiesResponse ReadSessionPropertiesResponse)
        {
            this.ReadSessionPropertiesResponse = ReadSessionPropertiesResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")]
    public partial class UpdateSessionProperties
    {
        
        private bool ignoreNullComplexFieldsField;
        
        private bool ignoreNullComplexFieldsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IgnoreNullComplexFields
        {
            get
            {
                return this.ignoreNullComplexFieldsField;
            }
            set
            {
                this.ignoreNullComplexFieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IgnoreNullComplexFieldsSpecified
        {
            get
            {
                return this.ignoreNullComplexFieldsFieldSpecified;
            }
            set
            {
                this.ignoreNullComplexFieldsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1")]
    public partial class UpdateSessionPropertiesResponse
    {
        
        private bool returnField;
        
        private bool returnFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Return
        {
            get
            {
                return this.returnField;
            }
            set
            {
                this.returnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReturnSpecified
        {
            get
            {
                return this.returnFieldSpecified;
            }
            set
            {
                this.returnFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSessionPropertiesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", Order=0)]
        public P6SOAP_AuthenticationService.UpdateSessionProperties UpdateSessionProperties;
        
        public UpdateSessionPropertiesRequest()
        {
        }
        
        public UpdateSessionPropertiesRequest(P6SOAP_AuthenticationService.UpdateSessionProperties UpdateSessionProperties)
        {
            this.UpdateSessionProperties = UpdateSessionProperties;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSessionPropertiesResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", Order=0)]
        public P6SOAP_AuthenticationService.UpdateSessionPropertiesResponse UpdateSessionPropertiesResponse;
        
        public UpdateSessionPropertiesResponse1()
        {
        }
        
        public UpdateSessionPropertiesResponse1(P6SOAP_AuthenticationService.UpdateSessionPropertiesResponse UpdateSessionPropertiesResponse)
        {
            this.UpdateSessionPropertiesResponse = UpdateSessionPropertiesResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface AuthenticationServicePortTypeChannel : P6SOAP_AuthenticationService.AuthenticationServicePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class AuthenticationServicePortTypeClient : System.ServiceModel.ClientBase<P6SOAP_AuthenticationService.AuthenticationServicePortType>, P6SOAP_AuthenticationService.AuthenticationServicePortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AuthenticationServicePortTypeClient() : 
                base(AuthenticationServicePortTypeClient.GetDefaultBinding(), AuthenticationServicePortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AuthenticationServiceSOAP12port_http.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationServicePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(AuthenticationServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), AuthenticationServicePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationServicePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AuthenticationServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationServicePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AuthenticationServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<P6SOAP_AuthenticationService.LoginResponse1> P6SOAP_AuthenticationService.AuthenticationServicePortType.LoginAsync(P6SOAP_AuthenticationService.LoginRequest request)
        {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<P6SOAP_AuthenticationService.LoginResponse1> LoginAsync(P6SOAP_AuthenticationService.Login Login)
        {
            P6SOAP_AuthenticationService.LoginRequest inValue = new P6SOAP_AuthenticationService.LoginRequest();
            inValue.Login = Login;
            return ((P6SOAP_AuthenticationService.AuthenticationServicePortType)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<P6SOAP_AuthenticationService.LogoutResponse1> P6SOAP_AuthenticationService.AuthenticationServicePortType.LogoutAsync(P6SOAP_AuthenticationService.LogoutRequest request)
        {
            return base.Channel.LogoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<P6SOAP_AuthenticationService.LogoutResponse1> LogoutAsync(object Logout)
        {
            P6SOAP_AuthenticationService.LogoutRequest inValue = new P6SOAP_AuthenticationService.LogoutRequest();
            inValue.Logout = Logout;
            return ((P6SOAP_AuthenticationService.AuthenticationServicePortType)(this)).LogoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<P6SOAP_AuthenticationService.ReadDatabaseInstancesResponse> P6SOAP_AuthenticationService.AuthenticationServicePortType.ReadDatabaseInstancesAsync(P6SOAP_AuthenticationService.ReadDatabaseInstancesRequest request)
        {
            return base.Channel.ReadDatabaseInstancesAsync(request);
        }
        
        public System.Threading.Tasks.Task<P6SOAP_AuthenticationService.ReadDatabaseInstancesResponse> ReadDatabaseInstancesAsync(object ReadDatabaseInstances)
        {
            P6SOAP_AuthenticationService.ReadDatabaseInstancesRequest inValue = new P6SOAP_AuthenticationService.ReadDatabaseInstancesRequest();
            inValue.ReadDatabaseInstances = ReadDatabaseInstances;
            return ((P6SOAP_AuthenticationService.AuthenticationServicePortType)(this)).ReadDatabaseInstancesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<P6SOAP_AuthenticationService.ReadSessionPropertiesResponse1> P6SOAP_AuthenticationService.AuthenticationServicePortType.ReadSessionPropertiesAsync(P6SOAP_AuthenticationService.ReadSessionPropertiesRequest request)
        {
            return base.Channel.ReadSessionPropertiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<P6SOAP_AuthenticationService.ReadSessionPropertiesResponse1> ReadSessionPropertiesAsync(object ReadSessionProperties)
        {
            P6SOAP_AuthenticationService.ReadSessionPropertiesRequest inValue = new P6SOAP_AuthenticationService.ReadSessionPropertiesRequest();
            inValue.ReadSessionProperties = ReadSessionProperties;
            return ((P6SOAP_AuthenticationService.AuthenticationServicePortType)(this)).ReadSessionPropertiesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<P6SOAP_AuthenticationService.UpdateSessionPropertiesResponse1> P6SOAP_AuthenticationService.AuthenticationServicePortType.UpdateSessionPropertiesAsync(P6SOAP_AuthenticationService.UpdateSessionPropertiesRequest request)
        {
            return base.Channel.UpdateSessionPropertiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<P6SOAP_AuthenticationService.UpdateSessionPropertiesResponse1> UpdateSessionPropertiesAsync(P6SOAP_AuthenticationService.UpdateSessionProperties UpdateSessionProperties)
        {
            P6SOAP_AuthenticationService.UpdateSessionPropertiesRequest inValue = new P6SOAP_AuthenticationService.UpdateSessionPropertiesRequest();
            inValue.UpdateSessionProperties = UpdateSessionProperties;
            return ((P6SOAP_AuthenticationService.AuthenticationServicePortType)(this)).UpdateSessionPropertiesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AuthenticationServiceSOAP12port_http))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AuthenticationServiceSOAP12port_http))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8206/p6ws/services/AuthenticationService");
            }

            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AuthenticationServicePortTypeClient.GetBindingForEndpoint(EndpointConfiguration.AuthenticationServiceSOAP12port_http);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AuthenticationServicePortTypeClient.GetEndpointAddress(EndpointConfiguration.AuthenticationServiceSOAP12port_http);
        }
        
        public enum EndpointConfiguration
        {
            
            AuthenticationServiceSOAP12port_http,
        }
    }
}
