using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Input;
using Autocad_Primavera_P6_Plugin.Services.P6ApiService;
using Autodesk.AutoCAD.DatabaseServices;
using PropertyChanged;

namespace Autocad_Primavera_P6_Plugin.UserInterface.UI_InsertBlocksWindowView
{
    public sealed class ACadBlockSectionModel
    {



    }

    [AddINotifyPropertyChangedInterface]
    public sealed class ACadBlockSectionViewModel
    {
        private readonly MyPlugin _pluginInstance;
        private readonly ACadBlockSectionModel _model;

        // Examples
        //public string SelectedCodeValue
        //{
        //    get => _model.SelectedCodeValue;
        //    set => _model.SelectedCodeValue = value;
        //}

        //public string ResolvedCodeValue => IsAutoGenerate ? AutoGeneratedCodeValue : SelectedCodeValue;


        public ACadBlockSectionViewModel(MyPlugin pluginInstance, Project project = null, BlockReference selectedBlock = null)
        {
            _model = new ACadBlockSectionModel
            {



            };
        }

        public async Task Async_Init()
        {
            await Task.CompletedTask;
        }

    }

}
