using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Input;
using Autocad_Primavera_P6_Plugin.Services.LiteDBService;
using Autocad_Primavera_P6_Plugin.Services.P6ApiService;
using Autodesk.AutoCAD.DatabaseServices;
using PropertyChanged;

namespace Autocad_Primavera_P6_Plugin.UserInterface.UI_InsertBlocksWindowView
{
    [AddINotifyPropertyChangedInterface]
    public sealed class ActivityCodeSectionViewModel
    {
        private readonly MyPlugin _pluginInstance;
        private Project _project;
        private BlockReference _preSelectedBlock;
        private ActivityCode _selectedActivityCode;
        private ActivityCode _autoGeneratedActivityCode;


        private P6ApiService _p6ApiService;
        private ActivityCodeType _activityCodeType = null;


        private ActivityCodeSectionModel _model;
        private ActivityCodePickerNodeViewModel _autoGenerateParentNode;
        private static readonly Random Random = new Random();

        public string SectionLabel { get; private set; } = "Element Id Code";
        public ICommand SelectCommand { get; private set; }

        public string SelectedCodeValue
        {
            get => _model.SelectedCodeValue;
            private set => _model.SelectedCodeValue = value;
        }

        public string SelectedCodePath
        {
            get => _model.SelectedCodePath;
            private set => _model.SelectedCodePath = value;
        }

        public string SelectedCodeValueId
        {
            get => _model.SelectedCodeValueId;
            private set => _model.SelectedCodeValueId = value;
        }

        public string AutoGeneratedCodeValue
        {
            get => _model.AutoGeneratedCodeValue;
            private set => _model.AutoGeneratedCodeValue = value;
        }

        public string AutoGeneratedCodePath
        {
            get => _model.AutoGeneratedCodePath;
            private set => _model.AutoGeneratedCodePath = value;
        }

        public string AutoGeneratedCodeValueId
        {
            get => _model.AutoGeneratedCodeValueId;
            private set => _model.AutoGeneratedCodeValueId = value;
        }

        public string Info
        {
            get => _model.Info;
            set => _model.Info = value;
        }

        public bool IsAutoGenerate
        {
            get => _model.IsAutoGenerate;
            set => _model.IsAutoGenerate = value;
        }

        public ActivityCode ResolvedActivityCode =>
            IsAutoGenerate ? _autoGeneratedActivityCode : _selectedActivityCode;

        public string ResolvedCodeValue => ResolvedActivityCode?.CodeValue ?? string.Empty;
        public string ResolvedCodePath => ResolvedActivityCode?.CodeConcatName ?? string.Empty;
        public string ResolvedCodeValueId => ResolvedActivityCode?.ObjectId?.ToString() ?? string.Empty;
        public bool HasResolvedCode => ResolvedActivityCode?.ObjectId.HasValue == true;
        public bool HasAutoGenerateParent => _autoGenerateParentNode != null;

        public ActivityCodeSectionViewModel(MyPlugin pluginInstance, Project project = null, BlockReference selectedBlock = null)
        {
            _model = new ActivityCodeSectionModel
            {
                Info = "-- Info --"
            };
            _pluginInstance = pluginInstance ?? throw new ArgumentNullException(nameof(pluginInstance));
            _project = project;
            _preSelectedBlock = selectedBlock;
            RefreshActivityCodeDisplay();
        }

        public async Task Async_Init()
        {
            _p6ApiService = _pluginInstance.MyP6ApiService;
            
            _activityCodeType = await _p6ApiService.GetP6ActivityCodeTypeOfProject(_project, _model.ActivtyCodeTypeName);

            SelectCommand = new RelayCommand(SelectCode);
        }

        private async void SelectCode(object parameter)
        {
            if (_activityCodeType == null)
            {
                Info = $"Activity-code type '{_model.ActivtyCodeTypeName}' is unavailable.";
                return;
            }

            var owner = parameter as Window;
            var pickerModel = new ActivityCodePickerModel(_pluginInstance, IsAutoGenerate, _activityCodeType);
            await pickerModel.AsyncInit();
            var picker = new ActivityCodePickerView(pickerModel);
            if (owner != null)
            {
                picker.Owner = owner;
            }

            bool? result = picker.ShowDialog();
            if (result != true || picker.ViewModel == null || picker.ViewModel.SelectedNode == null)
            {
                return;
            }

            var selectedNode = picker.ViewModel.SelectedNode;
            if (IsAutoGenerate)
            {
                _autoGenerateParentNode = selectedNode;
                _autoGeneratedActivityCode = null;
                RefreshActivityCodeDisplay();
                Info = "Ready to generate under: " + selectedNode.Path;
            }
            else
            {
                ResolveManualCode(selectedNode);
            }

            CommandManager.InvalidateRequerySuggested();
        }

        public Task<bool> EnsureResolvedAsync(bool forceRegenerate = false)
        {
            if (!IsAutoGenerate)
            {
                return Task.FromResult(HasResolvedCode);
            }

            if (HasResolvedCode && !forceRegenerate)
            {
                return Task.FromResult(true);
            }

            if (_autoGenerateParentNode == null)
            {
                Info = "Select a parent code first.";
                return Task.FromResult(false);
            }

            return AutoGenerateActivityCodeAsync(_autoGenerateParentNode);
        }

        public void CommitAutoGeneratedAsSelected()
        {
            if (!HasResolvedCode)
            {
                return;
            }

            _selectedActivityCode = _autoGeneratedActivityCode;
            IsAutoGenerate = false;
            RefreshActivityCodeDisplay();
            Info = "Selected: " + SelectedCodePath;
        }

        public void ResolveManualCode(ActivityCodePickerNodeViewModel selectedNode)
        {
            if (selectedNode == null || selectedNode.Code == null)
            {
                Info = "Select an activity code value.";
                return;
            }

            _selectedActivityCode = selectedNode.Code;
            RefreshActivityCodeDisplay();
            Info = "Selected: " + SelectedCodePath;
        }

        private async Task<bool> AutoGenerateActivityCodeAsync(ActivityCodePickerNodeViewModel parentNode)
        {
            try
            {
                if (_p6ApiService == null || _p6ApiService.Client == null)
                {
                    Info = "Failed: P6 is not connected.";
                    return false;
                }

                ActivityCodeType codeType = parentNode.CodeType;
                ActivityCode parentCode = parentNode.Code;

                if (parentCode != null)
                {
                    codeType = FindRootCodeType(parentNode);
                }

                if (codeType == null || !codeType.ObjectId.HasValue)
                {
                    Info = "Failed: selected parent has no code type id.";
                    return false;
                }

                string newValue = CreateGeneratedValue(codeType.Length);
                var newCode = new ActivityCode
                {
                    CodeTypeObjectId = codeType.ObjectId.Value,
                    CodeValue = newValue,
                    ParentObjectId = parentCode != null ? parentCode.ObjectId : null
                };

                string response = await _p6ApiService.Client
                    .CreateActivityCodeAsync(null, new[] { newCode })
                    .ConfigureAwait(true);

                int? createdObjectId = TryExtractObjectId(response);
                if (!createdObjectId.HasValue)
                {
                    Info = "P6 created the activity code but did not return its ObjectId.";
                    return false;
                }

                newCode.ObjectId = createdObjectId.Value;
                newCode.CodeConcatName = parentCode == null || string.IsNullOrWhiteSpace(parentCode.CodeConcatName)
                    ? newValue
                    : parentCode.CodeConcatName + "." + newValue;

                _autoGeneratedActivityCode = newCode;
                RefreshActivityCodeDisplay();
                Info = "Created: " + newValue;
                return true;
            }
            catch (Exception ex)
            {
                Info = "Failed: " + ex.Message;
                Debug.Print(ex.ToString());
                return false;
            }
        }

        private ActivityCodeType FindRootCodeType(ActivityCodePickerNodeViewModel node)
        {
            var cursor = node;
            while (cursor != null && !cursor.IsCodeType)
            {
                cursor = cursor.Parent;
            }

            return cursor == null ? null : cursor.CodeType;
        }

        private string CreateGeneratedValue(int? maxLength)
        {
            string prefix = SectionLabel.StartsWith("Boundary", StringComparison.OrdinalIgnoreCase) ? "BND" : "ITM";
            string value;

            lock (Random)
            {
                value = prefix + "-" + Guid.NewGuid().ToString("N").Substring(0, 8).ToUpperInvariant();
            }

            if (maxLength.HasValue && maxLength.Value > 0 && value.Length > maxLength.Value)
            {
                value = value.Substring(0, maxLength.Value);
            }

            return value;
        }

        private static int? TryExtractObjectId(string response)
        {
            if (string.IsNullOrWhiteSpace(response))
            {
                return null;
            }

            response = response.Trim().Trim('"');
            if (int.TryParse(response, out int directObjectId))
            {
                return directObjectId;
            }

            var match = Regex.Match(
                response,
                @"(?:ObjectId|Id)\D+(?<id>\d+)",
                RegexOptions.IgnoreCase);

            return match.Success && int.TryParse(match.Groups["id"].Value, out int parsedObjectId)
                ? parsedObjectId
                : null;
        }

        public void OnIsAutoGenerateChanged()
        {
            RefreshActivityCodeDisplay();
        }

        private void RefreshActivityCodeDisplay()
        {
            SelectedCodeValue = _selectedActivityCode?.CodeValue ?? "-- Code Value --";
            SelectedCodePath = _selectedActivityCode?.CodeConcatName ?? "-- Code Path --";
            SelectedCodeValueId = _selectedActivityCode?.ObjectId?.ToString() ?? "-- Code Value Id --";
            AutoGeneratedCodeValue = _autoGeneratedActivityCode?.CodeValue ?? string.Empty;
            AutoGeneratedCodePath = _autoGeneratedActivityCode?.CodeConcatName ?? string.Empty;
            AutoGeneratedCodeValueId = _autoGeneratedActivityCode?.ObjectId?.ToString() ?? string.Empty;
        }
    }
}
