using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Input;
using Autocad_Primavera_P6_Plugin.Services.LiteDBService;
using Autocad_Primavera_P6_Plugin.Services.P6ApiService;
using Autodesk.AutoCAD.DatabaseServices;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;

namespace Autocad_Primavera_P6_Plugin.UserInterface.UI_InsertBlocksWindowView
{
    public partial class BoundaryActivityCodeSectionViewModel: ObservableObject
    {
        private readonly MyPlugin _pluginInstance;
        private P6ApiService P6ApiService => _pluginInstance.MyP6ApiService;

        private Project Project;

        private readonly string ActivityCodeTypeName = "Boundary";

        [ObservableProperty]
        [NotifyPropertyChangedFor(nameof(SelectedCodeValue))]
        [NotifyPropertyChangedFor(nameof(SelectedCodeDescription))]
        [NotifyPropertyChangedFor(nameof(SelectedCodePath))]
        [NotifyPropertyChangedFor(nameof(SelectedCodeValueId))]
        [NotifyPropertyChangedFor(nameof(CanAutoGenerate))]
        public ActivityCode _selectedActivityCode;

        private ActivityCodePickerNodeViewModel SelectedActivityCodeNode;

        public string SelectedCodeValue => SelectedActivityCode?.CodeValue ?? "";
        public string SelectedCodeDescription => SelectedActivityCode?.Description ?? "";
        public string SelectedCodePath => SelectedActivityCode?.CodeConcatName ?? "";
        public string SelectedCodeValueId => SelectedActivityCode?.ObjectId?.ToString() ?? "";

        public bool CanAutoGenerate => SelectedActivityCode != null &&
            SelectedActivityCode.ObjectId != null &&
            SelectedActivityCode.CodeValue != null &&
            SelectedActivityCode.Description != null &&
            SelectedActivityCode.CodeConcatName != null;

        [ObservableProperty]
        public bool _isAutoGenerate;

        [ObservableProperty]
        private ActivityCode _autoGeneratedActivityCode = new();

        [ObservableProperty]
        private ActivityCodeType _boundaryActivityCodeType = null;

        public string SectionLabel { get; private set; } = "Boundary Code";

        [ObservableProperty]
        public string _info = "-- Info --";


        public BoundaryActivityCodeSectionViewModel(MyPlugin pluginInstance, Project project = null, BlockReference selectedBlock = null)
        {
            _pluginInstance = pluginInstance ?? throw new ArgumentNullException(nameof(pluginInstance));
            Project = project;
        }

        public async Task Async_Init()
        {
            BoundaryActivityCodeType = await P6ApiService.GetP6ActivityCodeTypeOfProject(Project, ActivityCodeTypeName);
        }

        [RelayCommand]
        private async Task SelectCodeAsync(object parameter)
        {
            if (BoundaryActivityCodeType == null)
            {
                Info = $"Activity-code type '{ActivityCodeTypeName}' is unavailable.";
                return;
            }
            
            var owner = parameter as Window;

            var pickerModel = new ActivityCodePickerModel(_pluginInstance, IsAutoGenerate, BoundaryActivityCodeType);
            await pickerModel.AsyncInit();
            var picker = new ActivityCodePickerView(pickerModel);

            if (owner != null)
            {
                picker.Owner = owner;
            }

            bool? result = picker.ShowDialog();
            if (result != true || picker.ViewModel == null || picker.ViewModel.SelectedNode == null)
            {
                return;
            }

            var selectedNode = picker.ViewModel.SelectedNode;
            SelectedActivityCodeNode = picker.ViewModel.SelectedNode;

            if (IsAutoGenerate)
            {
                AutoGeneratedActivityCode = null;
                Info = "Ready to generate under: " + selectedNode.Path;
            }
            else
            {
                ResolveManualCode(selectedNode);
            }

            CommandManager.InvalidateRequerySuggested();
        }

        [RelayCommand]
        private async Task<bool> AutoGenerateActivityCodeAsync(ActivityCodePickerNodeViewModel parentNode)
        {
            try
            {
                if (P6ApiService == null || P6ApiService.Client == null)
                {
                    Info = "Failed: P6 is not connected.";
                    return false;
                }

                ActivityCodeType codeType = parentNode.CodeType;
                ActivityCode parentCode = parentNode.Code;

                if (parentCode != null)
                {
                    codeType = FindRootCodeType(parentNode);
                }

                if (codeType == null || !codeType.ObjectId.HasValue)
                {
                    Info = "Failed: selected parent has no code type id.";
                    return false;
                }

                string newValue = CreateGeneratedValue(codeType.Length);
                var newCode = new ActivityCode
                {
                    CodeTypeObjectId = codeType.ObjectId.Value,
                    CodeValue = newValue,
                    ParentObjectId = parentCode != null ? parentCode.ObjectId : null
                };

                string response = await P6ApiService.Client
                    .CreateActivityCodeAsync(null, new[] { newCode })
                    .ConfigureAwait(true);

                int? createdObjectId = TryExtractObjectId(response);
                if (!createdObjectId.HasValue)
                {
                    Info = "P6 created the activity code but did not return its ObjectId.";
                    return false;
                }

                newCode.ObjectId = createdObjectId.Value;
                newCode.CodeConcatName = parentCode == null || string.IsNullOrWhiteSpace(parentCode.CodeConcatName)
                    ? newValue
                    : parentCode.CodeConcatName + "." + newValue;

                AutoGeneratedActivityCode = newCode;
                Info = "Created: " + newValue;
                return true;
            }
            catch (Exception ex)
            {
                Info = "Failed: " + ex.Message;
                SelectedActivityCodeNode = null;
                SelectedActivityCode = null;

                Debug.Print(ex.ToString());
                return false;
            }
        }

        public void ResolveManualCode(ActivityCodePickerNodeViewModel selectedNode)
        {
            if (selectedNode == null || selectedNode.Code == null)
            {
                Info = "Select an activity code value.";
                return;
            }

            SelectedActivityCode = selectedNode.Code;
            SelectedActivityCodeNode = selectedNode;
            Info = "Selected: " + SelectedCodePath;
        }

        private ActivityCodeType FindRootCodeType(ActivityCodePickerNodeViewModel node)
        {
            var cursor = node;
            while (cursor != null && !cursor.IsCodeType)
            {
                cursor = cursor.Parent;
            }

            return cursor == null ? null : cursor.CodeType;
        }

        private string CreateGeneratedValue(int? maxLength)
        {
            string prefix = SectionLabel.StartsWith("Boundary", StringComparison.OrdinalIgnoreCase) ? "BND" : "ITM";
            string value;

            value = prefix + "-" + Guid.NewGuid().ToString("N").Substring(0, 8).ToUpperInvariant();

            if (maxLength.HasValue && maxLength.Value > 0 && value.Length > maxLength.Value)
            {
                value = value.Substring(0, maxLength.Value);
            }

            return value;
        }

        private static int? TryExtractObjectId(string response)
        {
            if (string.IsNullOrWhiteSpace(response))
            {
                return null;
            }

            response = response.Trim().Trim('"');
            if (int.TryParse(response, out int directObjectId))
            {
                return directObjectId;
            }

            var match = Regex.Match(
                response,
                @"(?:ObjectId|Id)\D+(?<id>\d+)",
                RegexOptions.IgnoreCase);

            return match.Success && int.TryParse(match.Groups["id"].Value, out int parsedObjectId)
                ? parsedObjectId
                : null;
        }

        public void OnIsAutoGenerateChanged()
        {
            // Reset the auto-generated code when switching modes
            Info = "New Boundary Activity Code Generated Successfully";
        }

    }

    public class AsyncRelayCommand : ICommand
    {
        private readonly Func<Task> _execute;
        private readonly Func<bool> _canExecute;
        private bool _isExecuting;

        public AsyncRelayCommand(Func<Task> execute, Func<bool> canExecute = null)
        {
            _execute = execute ?? throw new ArgumentNullException(nameof(execute));
            _canExecute = canExecute;
        }

        public event EventHandler CanExecuteChanged
        {
            add => CommandManager.RequerySuggested += value;
            remove => CommandManager.RequerySuggested -= value;
        }

        public bool CanExecute(object parameter)
        {
            // Disables the button automatically if the task is currently running
            return !_isExecuting && (_canExecute == null || _canExecute());
        }

        public async void Execute(object parameter)
        {
            _isExecuting = true;
            CommandManager.InvalidateRequerySuggested(); // Refresh UI button state

            try
            {
                await _execute();
            }
            finally
            {
                _isExecuting = false;
                CommandManager.InvalidateRequerySuggested(); // Re-enable button
            }
        }
    }

}
