using Autocad_Primavera_P6_Plugin.Services.LiteDBService;
using Autocad_Primavera_P6_Plugin.Services.P6ApiService;
using Autodesk.AutoCAD.DatabaseServices;
using Autodesk.AutoCAD.GraphicsSystem;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Linq.Expressions;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Input;
using static System.Net.Mime.MediaTypeNames;

namespace Autocad_Primavera_P6_Plugin.UserInterface.UI_InsertBlocksWindowView
{
    public partial class BoundaryActivityCodeSectionViewModel: ObservableObject
    {
        private readonly MyPlugin _pluginInstance;
        private P6ApiService P6ApiService => _pluginInstance.MyP6ApiService;

        private Project Project;

        private readonly string ActivityCodeTypeName = "Boundary";

        [ObservableProperty]
        [NotifyPropertyChangedFor(nameof(SelectedCodeValue))]
        [NotifyPropertyChangedFor(nameof(SelectedCodeDescription))]
        [NotifyPropertyChangedFor(nameof(SelectedCodePath))]
        [NotifyPropertyChangedFor(nameof(SelectedCodeValueId))]
        [NotifyPropertyChangedFor(nameof(CanAutoGenerate))]
        [NotifyCanExecuteChangedFor(nameof(AutoGenerateActivityCodeCommand))]
        public ActivityCode _selectedActivityCode;

        [ObservableProperty]
        [NotifyCanExecuteChangedFor(nameof(AutoGenerateActivityCodeCommand))]
        private ActivityCodePickerNodeViewModel _selectedActivityCodeNode;

        public string SelectedCodeValue => SelectedActivityCode?.CodeValue ?? "";
        public string SelectedCodeDescription => SelectedActivityCode?.Description ?? "";
        public string SelectedCodePath => SelectedActivityCode?.CodeConcatName ?? "";
        public string SelectedCodeValueId => SelectedActivityCode?.ObjectId?.ToString() ?? "";

        public bool CanAutoGenerate => SelectedActivityCode != null &&
            SelectedActivityCode.ObjectId != null &&
            SelectedActivityCode.CodeValue != null &&
            SelectedActivityCode.Description != null &&
            SelectedActivityCode.CodeConcatName != null;

        [ObservableProperty]
        public bool _isAutoGenerate;

        [ObservableProperty]
        [NotifyCanExecuteChangedFor(nameof(AutoGenerateActivityCodeCommand))]
        public string _userEnteredValue = String.Empty;

        [ObservableProperty]
        [NotifyCanExecuteChangedFor(nameof(AutoGenerateActivityCodeCommand))]
        public string _userEnteredDescription = String.Empty;

        [ObservableProperty]
        private ActivityCode _autoGeneratedActivityCode = new();

        [ObservableProperty]
        private ActivityCodeType _boundaryActivityCodeType = null;

        public string SectionLabel { get; private set; } = "Boundary Code";

        [ObservableProperty]
        public string _info = "-- Info --";

        public BoundaryActivityCodeSectionViewModel(MyPlugin pluginInstance, Project project = null, ActivityCode preSelectedCode = null)
        {
            _pluginInstance = pluginInstance ?? throw new ArgumentNullException(nameof(pluginInstance));
            Project = project;
            SelectedActivityCode = preSelectedCode;
        }

        public async Task Async_Init()
        {
            BoundaryActivityCodeType = await P6ApiService.GetP6ActivityCodeTypeOfProject(Project, ActivityCodeTypeName);

            var pickerModel = new ActivityCodePickerModel(_pluginInstance, IsAutoGenerate, BoundaryActivityCodeType);
            await pickerModel.AsyncInit();

            var activityCodePicker = new ActivityCodePickerView(pickerModel);
            SelectedActivityCodeNode = SelectedActivityCode != null
                ? activityCodePicker.ViewModel.GetNodeByActivityCode(SelectedActivityCode)
                : null;
        }

        [RelayCommand]
        private async Task SelectCodeAsync(object parameter)
        {
            if (BoundaryActivityCodeType == null)
            {
                Info = $"Activity-code type '{ActivityCodeTypeName}' is unavailable.";
                return;
            }

            var pickerModel = new ActivityCodePickerModel(_pluginInstance, IsAutoGenerate, BoundaryActivityCodeType);
            await pickerModel.AsyncInit();
            var activityCodePicker = new ActivityCodePickerView(pickerModel);

            var owner = parameter as Window;

            if (owner != null)
            {
                activityCodePicker.Owner = owner;
            }

            bool? result = activityCodePicker.ShowDialog();
            if (result != true || activityCodePicker.ViewModel == null || activityCodePicker.ViewModel.SelectedNode == null)
            {
                return;
            }

            SelectedActivityCodeNode = activityCodePicker.ViewModel.SelectedNode;
            SelectedActivityCode = SelectedActivityCodeNode.Code;

            Info = "Selected: " + SelectedCodePath;

            if (IsAutoGenerate)
            {
                // Revalidate AutoGeneratedActivityCode when switching to auto-generate mode
            }

            CommandManager.InvalidateRequerySuggested();
        }


        private bool AutoGenerateCanExicute()
        {
            if (!IsAutoGenerate) { return false; };

            if (UserEnteredValue == null || string.IsNullOrWhiteSpace(UserEnteredValue.Trim())) { Info = "Enter Valid Value Text"; return false; };

            if (UserEnteredDescription == null || string.IsNullOrWhiteSpace(UserEnteredDescription.Trim())) { Info = "Enter Valid Description Text"; return false; };

            var checkNoDuplicateValueList = SelectedActivityCodeNode
                .Children
                .Cast<ActivityCodePickerNodeViewModel>()
                .Select(node => node.Code.CodeValue)
                .ToList();

            var checkResult = checkNoDuplicateValueList.Contains(UserEnteredValue.Trim());

            if (checkResult)
            {
                Info = "Entered Value Already Exist";
                return false;
            }
            else
            {
                return true;
            };
        }


        [RelayCommand(CanExecute = nameof(AutoGenerateCanExicute))]
        private async Task<bool> AutoGenerateActivityCodeAsync(object parameter)
        {
            try
            {
                if (P6ApiService == null || P6ApiService.Client == null)
                {
                    Info = "Failed: P6 is not connected.";
                    return false;
                }

                if(SelectedActivityCodeNode == null || SelectedActivityCode == null)
                {
                    Info = "Select a parent code first.";
                    return false;
                }

                ActivityCode newCode = new ActivityCode()
                {
                    ParentObjectId = SelectedActivityCodeNode.Code.ObjectId,
                    CodeTypeObjectId = SelectedActivityCode.CodeTypeObjectId,
                    CodeValue = UserEnteredValue,
                    Description = UserEnteredDescription
                };

                // Code generated
                var result = await P6ApiService.Client.CreateActivityCodeAsync(null, new[] { newCode });

                var generatedCodeId = result.FirstOrDefault();

                if (generatedCodeId == null ||  string.IsNullOrWhiteSpace(generatedCodeId)) { throw new Exception("Unable to create new activity code"); };

                newCode.ObjectId = int.Parse(generatedCodeId);

                var pickerModel = new ActivityCodePickerModel(_pluginInstance, IsAutoGenerate, BoundaryActivityCodeType);
                await pickerModel.AsyncInit();
                var activityCodePicker = new ActivityCodePickerView(pickerModel);

                SelectedActivityCodeNode = activityCodePicker.ViewModel.GetNodeByActivityCode(newCode);
                SelectedActivityCode = SelectedActivityCodeNode?.Code;

                UserEnteredValue = String.Empty;
                UserEnteredDescription = String.Empty;
                IsAutoGenerate = false;

                Info = $"Successfully Generated New Boundary Code at {SelectedActivityCode.CodeConcatName}";

                return true;
            }
            catch (Exception ex)
            {
                Info = "Failed: " + ex.Message;

                Debug.Print(ex.ToString());
                return false;
            }
        }

    }

    public class AsyncRelayCommand : ICommand
    {
        private readonly Func<Task> _execute;
        private readonly Func<bool> _canExecute;
        private bool _isExecuting;

        public AsyncRelayCommand(Func<Task> execute, Func<bool> canExecute = null)
        {
            _execute = execute ?? throw new ArgumentNullException(nameof(execute));
            _canExecute = canExecute;
        }

        public event EventHandler CanExecuteChanged
        {
            add => CommandManager.RequerySuggested += value;
            remove => CommandManager.RequerySuggested -= value;
        }

        public bool CanExecute(object parameter)
        {
            // Disables the button automatically if the task is currently running
            return !_isExecuting && (_canExecute == null || _canExecute());
        }

        public async void Execute(object parameter)
        {
            _isExecuting = true;
            CommandManager.InvalidateRequerySuggested(); // Refresh UI button state

            try
            {
                await _execute();
            }
            finally
            {
                _isExecuting = false;
                CommandManager.InvalidateRequerySuggested(); // Re-enable button
            }
        }
    }

}
