using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Input;
using Autocad_Primavera_P6_Plugin.Services.LiteDBService;
using Autocad_Primavera_P6_Plugin.Services.P6ApiService;
using PropertyChanged;

namespace Autocad_Primavera_P6_Plugin.UserInterface.UI_InsertBlocksWindowView
{
    [AddINotifyPropertyChangedInterface]
    public sealed class BoundryActivityCodeSectionViewModel
    {
        private readonly MyPlugin _pluginInstance;

        private readonly P6ApiService _p6ApiService;
        private Project _project;

        private string _activtyCodeTypeName = "Boundary Code";

        private ActivityCodeType _activtyCodeType = null;



        private readonly ActivityCodeSectionModel _model;

        private ActivityCodePickerNodeViewModel _autoGenerateParentNode;
        private static readonly Random Random = new Random();

        public string SectionLabel { get; private set; } = "BND";
        public ICommand SelectCommand { get; private set; }



        public string SelectedCodeValue
        {
            get => _model.SelectedCodeValue;
            set => _model.SelectedCodeValue = value;
        }

        public string SelectedCodePath
        {
            get => _model.SelectedCodePath;
            set => _model.SelectedCodePath = value;
        }

        public string SelectedCodeValueId
        {
            get => _model.SelectedCodeValueId;
            set => _model.SelectedCodeValueId = value;
        }

        public string AutoGeneratedCodeValue
        {
            get => _model.AutoGeneratedCodeValue;
            set => _model.AutoGeneratedCodeValue = value;
        }

        public string AutoGeneratedCodePath
        {
            get => _model.AutoGeneratedCodePath;
            set => _model.AutoGeneratedCodePath = value;
        }

        public string AutoGeneratedCodeValueId
        {
            get => _model.AutoGeneratedCodeValueId;
            set => _model.AutoGeneratedCodeValueId = value;
        }

        public string Info
        {
            get => _model.Info;
            set => _model.Info = value;
        }

        public bool IsAutoGenerate
        {
            get => _model.IsAutoGenerate;
            set => _model.IsAutoGenerate = value;
        }

        public string ResolvedCodeValue => IsAutoGenerate ? AutoGeneratedCodeValue : SelectedCodeValue;
        public string ResolvedCodePath => IsAutoGenerate ? AutoGeneratedCodePath : SelectedCodePath;
        public string ResolvedCodeValueId => IsAutoGenerate ? AutoGeneratedCodeValueId : SelectedCodeValueId;
        public bool HasResolvedCode => !string.IsNullOrWhiteSpace(ResolvedCodeValue);
        public bool HasAutoGenerateParent => _autoGenerateParentNode != null;


        public BoundryActivityCodeSectionViewModel(MyPlugin pluginInstance, Project project = null)
        {
            _pluginInstance = pluginInstance ?? throw new ArgumentNullException(nameof(pluginInstance));
            _p6ApiService = _pluginInstance.MyP6ApiService;
            _project = project;
            InitializeAsync().ConfigureAwait(true);
            _model = new ActivityCodeSectionModel
            {
                SelectedCodeValue = "-- Code Value --",
                SelectedCodePath = "-- Code Path --",
                SelectedCodeValueId = "-- Code Value Id --",
                AutoGeneratedCodeValue = string.Empty,
                AutoGeneratedCodePath = string.Empty,
                AutoGeneratedCodeValueId = string.Empty,
                Info = "-- Info --"
            };
            SelectCommand = new RelayCommand(SelectCode);
        }

        private async Task InitializeAsync()
        {
            _activtyCodeType = await _p6ApiService.GetP6ActivityCodeTypeOfProject(_project, _activtyCodeTypeName);
        }

        private async void SelectCode(object parameter)
        {
            var owner = parameter as Window;

            var pickerModel = new ActivityCodePickerModel(_pluginInstance, IsAutoGenerate, _activtyCodeType);
            await pickerModel.AsyncInit();
            var picker = new ActivityCodePickerView(new ActivityCodePickerModel(_pluginInstance, IsAutoGenerate, _activtyCodeType));
            if (owner != null)
            {
                picker.Owner = owner;
            }

            bool? result = picker.ShowDialog();
            if (result != true || picker.ViewModel == null || picker.ViewModel.SelectedNode == null)
            {
                return;
            }

            var selectedNode = picker.ViewModel.SelectedNode;
            if (IsAutoGenerate)
            {
                _autoGenerateParentNode = selectedNode;
                AutoGeneratedCodeValue = string.Empty;
                AutoGeneratedCodePath = string.Empty;
                AutoGeneratedCodeValueId = string.Empty;
                Info = "Ready to generate under: " + selectedNode.Path;
            }
            else
            {
                ResolveManualCode(selectedNode);
            }

            CommandManager.InvalidateRequerySuggested();
        }

        public Task<bool> EnsureResolvedAsync(bool forceRegenerate = false)
        {
            if (!IsAutoGenerate)
            {
                return Task.FromResult(HasResolvedCode);
            }

            if (HasResolvedCode && !forceRegenerate)
            {
                return Task.FromResult(true);
            }

            if (_autoGenerateParentNode == null)
            {
                Info = "Select a parent code first.";
                return Task.FromResult(false);
            }

            return AutoGenerateActivityCodeAsync(_autoGenerateParentNode);
        }

        public void CommitAutoGeneratedAsSelected()
        {
            if (!HasResolvedCode)
            {
                return;
            }

            SelectedCodeValue = AutoGeneratedCodeValue;
            SelectedCodePath = AutoGeneratedCodePath;
            SelectedCodeValueId = AutoGeneratedCodeValueId;
            IsAutoGenerate = false;
            Info = "Selected: " + SelectedCodePath;
        }

        public void ResolveManualCode(ActivityCodePickerNodeViewModel selectedNode)
        {
            if (selectedNode == null || selectedNode.Code == null)
            {
                Info = "Select an activity code value.";
                return;
            }

            var code = selectedNode.Code;
            SelectedCodeValue = code.CodeValue;
            SelectedCodePath = !string.IsNullOrWhiteSpace(code.CodeConcatName) ? code.CodeConcatName : selectedNode.Path;
            SelectedCodeValueId = code.ObjectId.HasValue ? code.ObjectId.Value.ToString() : string.Empty;
            Info = "Selected: " + SelectedCodePath;
        }

        private async Task<bool> AutoGenerateActivityCodeAsync(ActivityCodePickerNodeViewModel parentNode)
        {
            try
            {
                if (_p6ApiService == null || _p6ApiService.Client == null)
                {
                    Info = "Failed: P6 is not connected.";
                    return false;
                }

                ActivityCodeType codeType = parentNode.CodeType;
                ActivityCode parentCode = parentNode.Code;

                if (parentCode != null)
                {
                    codeType = FindRootCodeType(parentNode);
                }

                if (codeType == null || !codeType.ObjectId.HasValue)
                {
                    Info = "Failed: selected parent has no code type id.";
                    return false;
                }

                string newValue = CreateGeneratedValue(codeType.Length);
                var newCode = new ActivityCode
                {
                    CodeTypeObjectId = codeType.ObjectId.Value,
                    CodeValue = newValue,
                    ParentObjectId = parentCode != null ? parentCode.ObjectId : null
                };

                string response = await _p6ApiService.Client
                    .CreateActivityCodeAsync(null, new[] { newCode })
                    .ConfigureAwait(true);

                AutoGeneratedCodeValue = newValue;
                AutoGeneratedCodePath = string.IsNullOrWhiteSpace(parentNode.Path) ? newValue : parentNode.Path + " / " + newValue;
                AutoGeneratedCodeValueId = TryExtractObjectId(response);
                Info = "Created: " + newValue;
                return true;
            }
            catch (Exception ex)
            {
                Info = "Failed: " + ex.Message;
                Debug.Print(ex.ToString());
                return false;
            }
        }

        private ActivityCodeType FindRootCodeType(ActivityCodePickerNodeViewModel node)
        {
            var cursor = node;
            while (cursor != null && !cursor.IsCodeType)
            {
                cursor = cursor.Parent;
            }

            return cursor == null ? null : cursor.CodeType;
        }

        private string CreateGeneratedValue(int? maxLength)
        {
            string prefix = SectionLabel.StartsWith("Boundary", StringComparison.OrdinalIgnoreCase) ? "BND" : "ITM";
            string value;

            lock (Random)
            {
                value = prefix + "-" + Guid.NewGuid().ToString("N").Substring(0, 8).ToUpperInvariant();
            }

            if (maxLength.HasValue && maxLength.Value > 0 && value.Length > maxLength.Value)
            {
                value = value.Substring(0, maxLength.Value);
            }

            return value;
        }

        private string TryExtractObjectId(string response)
        {
            if (string.IsNullOrWhiteSpace(response))
            {
                return string.Empty;
            }

            var digits = new string(response.Where(char.IsDigit).ToArray());
            return string.IsNullOrWhiteSpace(digits) ? response : digits;
        }
    }

    public class AsyncRelayCommand : ICommand
    {
        private readonly Func<Task> _execute;
        private readonly Func<bool> _canExecute;
        private bool _isExecuting;

        public AsyncRelayCommand(Func<Task> execute, Func<bool> canExecute = null)
        {
            _execute = execute ?? throw new ArgumentNullException(nameof(execute));
            _canExecute = canExecute;
        }

        public event EventHandler CanExecuteChanged
        {
            add => CommandManager.RequerySuggested += value;
            remove => CommandManager.RequerySuggested -= value;
        }

        public bool CanExecute(object parameter)
        {
            // Disables the button automatically if the task is currently running
            return !_isExecuting && (_canExecute == null || _canExecute());
        }

        public async void Execute(object parameter)
        {
            _isExecuting = true;
            CommandManager.InvalidateRequerySuggested(); // Refresh UI button state

            try
            {
                await _execute();
            }
            finally
            {
                _isExecuting = false;
                CommandManager.InvalidateRequerySuggested(); // Re-enable button
            }
        }
    }

}
