using Autocad_Primavera_P6_Plugin.Services.P6ApiService;
using Autocad_Primavera_P6_Plugin.UserInterface.UI_InsertBlocksWindowView.ActivityCodePicker;
using Autocad_Primavera_P6_Plugin.UserInterface.UI_InsertBlocksWindowView.CopyActivityOptionsPicker;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Input;

namespace Autocad_Primavera_P6_Plugin.UserInterface.UI_InsertBlocksWindowView
{
    /// <summary>
    /// ViewModel for Element ID Code selection and auto-generation.
    /// 
    /// Two modes:
    ///   NUMERIC: Selected code's value is numeric (e.g., "3") → auto-generate siblings 4, 5, 6...
    ///   TEXT: Selected code's value is text (e.g., "Branch_A") → create new branch, then numeric leaves under it
    /// </summary>
    /// 
    public partial class ElementIdCodeSectionViewModel : ObservableObject
    {
        private readonly MyPlugin _pluginInstance;
        private P6ApiService _p6ApiService => _pluginInstance.MyP6ApiService;

        private Project Project;

        [ObservableProperty]
        public bool _isAutoGenerateLoop;

        private bool _isBranchLocked;

        private readonly string ActivityCodeTypeName = "Element Id";

        [ObservableProperty]
        public ActivityCode _selectedActivityCode;

        [ObservableProperty]
        private ActivityCodePickerNodeViewModel _selectedActivityCodeNode;

        public string SelectedCodeValue => SelectedActivityCode?.CodeValue ?? "";
        public string SelectedCodeDescription => SelectedActivityCode?.Description ?? "";
        public string SelectedCodePath => SelectedActivityCode?.CodeConcatName ?? "";
        public string SelectedCodeValueId => SelectedActivityCode?.ObjectId?.ToString() ?? "";


        public bool IsNumericSelection => SelectedActivityCode != null && int.TryParse(SelectedActivityCode.CodeValue, out _);
        public bool IsTextSelection => SelectedActivityCode != null && !IsNumericSelection;
        public System.Windows.Visibility IsNumericSelectionVisibility => IsNumericSelection ? System.Windows.Visibility.Visible : System.Windows.Visibility.Collapsed;
        public System.Windows.Visibility IsTextSelectionVisibility => !IsNumericSelection ? System.Windows.Visibility.Visible : System.Windows.Visibility.Collapsed;


        public bool CanAutoGenerate => SelectedActivityCode != null &&
            SelectedActivityCode.ObjectId != null &&
            SelectedActivityCode.CodeValue != null &&
            SelectedActivityCode.Description != null &&
            SelectedActivityCode.CodeConcatName != null;

        [ObservableProperty]
        [NotifyPropertyChangedFor(nameof(CanEditValue))]
        [NotifyPropertyChangedFor(nameof(CanEditDescription))]
        [NotifyPropertyChangedFor(nameof(ShowGenerateFirstLeafButton))]
        [NotifyPropertyChangedFor(nameof(GenerateFirstLeafVisibility))]
        public bool _isAutoGenerate;

        public string NextNumericValue => IsNumericSelection || ShowGenerateFirstLeafButton ? GetNextNumericValue().ToString() : String.Empty;
        public bool CanEditValue => IsAutoGenerate && IsTextSelection && !_isBranchLocked;
        public bool CanEditDescription => IsAutoGenerate && !_isBranchLocked;
        public bool ShowGenerateFirstLeafButton => IsAutoGenerate && IsTextSelection && !IsAutoGenerateLoop && !SelectedActivityCodeNode.Children.Any();
        public System.Windows.Visibility GenerateFirstLeafVisibility => ShowGenerateFirstLeafButton ? System.Windows.Visibility.Visible : System.Windows.Visibility.Collapsed;


        [ObservableProperty]
        [NotifyCanExecuteChangedFor(nameof(GenerateFirstLeafCommand))]
        [NotifyCanExecuteChangedFor(nameof(AutoGenerateActivityCodeCommand))]
        public string _userEnteredValue = String.Empty;

        [ObservableProperty]
        [NotifyCanExecuteChangedFor(nameof(GenerateFirstLeafCommand))]
        [NotifyCanExecuteChangedFor(nameof(AutoGenerateActivityCodeCommand))]
        public string _userEnteredDescription = "{index}";

        [ObservableProperty]
        private ActivityCode _autoGeneratedActivityCode = new();

        [ObservableProperty]
        private ActivityCodeType _elementIdActivityCodeType = null;

        public string SectionLabel { get; private set; } = "Element Id Code";

        [ObservableProperty]
        public string _info = "-- Info --";

        [ObservableProperty]
        public bool _isCopyActivities;

        [RelayCommand]
        public async Task ManageCopyActivitiesOptionsAsync(object parameter)
        {
            var _vm = new CopyActivityOptionsPickerViewModel();
            var _view = new CopyActivityOptionsPickerView(_vm);

            var owner = parameter as Window;
            if (owner != null) { _view.Owner = owner; };

            bool? result = _view.ShowDialog();
        }

        public ElementIdCodeSectionViewModel(MyPlugin pluginInstance, Project project = null, ActivityCode preSelectedCode = null)
        {
            _pluginInstance = pluginInstance ?? throw new ArgumentNullException(nameof(pluginInstance));
            Project = project;
            SelectedActivityCode = preSelectedCode;
        }

        public async Task Async_Init()
        {
            ElementIdActivityCodeType = await _p6ApiService.GetP6ActivityCodeTypeOfProject(Project, ActivityCodeTypeName);

            var pickerVM = new ActivityCodePickerViewModel(
                new ActivityCodePickerModel(_pluginInstance, IsAutoGenerate, ElementIdActivityCodeType)
            );
            await pickerVM.AsyncInit(project: Project, types: new() { ElementIdActivityCodeType });

            SelectedActivityCodeNode = SelectedActivityCode != null
                ? pickerVM.GetNodeByActivityCode(SelectedActivityCode)
                : null;
        }

        [RelayCommand]
        private async Task<bool> SelectCodeNodeAsync(object parameter)
        {
            if (ElementIdActivityCodeType == null)
            {
                Info = $"Activity-code type '{ActivityCodeTypeName}' is unavailable.";
                return false;
            }

            var pickerVM = new ActivityCodePickerViewModel(
                new ActivityCodePickerModel(_pluginInstance, IsAutoGenerate, ElementIdActivityCodeType)
            );
            await pickerVM.AsyncInit(project: Project, types: new() { ElementIdActivityCodeType });

            var activityCodePicker = new ActivityCodePickerView(pickerVM);

            var owner = parameter as Window;
            if (owner != null) { activityCodePicker.Owner = owner; }
            ;

            bool? result = activityCodePicker.ShowDialog();
            if (result != true || activityCodePicker.ViewModel == null || activityCodePicker.ViewModel.SelectedNode == null) { return false; };

            SelectedActivityCodeNode = activityCodePicker.ViewModel.SelectedNode;
            SelectedActivityCode = SelectedActivityCodeNode.Code;
            Info = "Selected: " + SelectedCodePath;

            OnPropertyChanged(string.Empty);
            return true;
        }


        [RelayCommand(CanExecute = nameof(AutoGenerateCanExecute))]
        public async Task<bool> AutoGenerateActivityCodeAsync(object parameter = null)
        {
            try
            {
                if (IsNumericSelection)
                {
                    await GenerateNumericAsync();
                }
                else
                {
                    await GenerateTextAsync();
                }

                return true;
            }
            catch (Exception ex)
            {
                Info = ex.Message;
                Debug.Print(ex.ToString());

                return false;
            }
        }

        [RelayCommand(CanExecute = nameof(CanGenerateFirstLeaf))]
        private async Task GenerateFirstLeafAsync()
        {
            ActivityCode firstLeaf = await CreateFirstLeafAsync();

            await RefreshSelectionAsync(firstLeaf);
        }

        private async Task GenerateNumericAsync()
        {
            int nextValue = GetNextNumericValue();

            string description = BuildDescription(nextValue.ToString());

            ActivityCode generatedCode = await CreateActivityCodeAsync(
                    parentObjectId: SelectedActivityCodeNode.Parent.Code.ObjectId.Value,
                    codeValue: nextValue.ToString(),
                    description: description
                    );

            await RefreshSelectionAsync(generatedCode);

            Info = $"Generated {generatedCode.CodeConcatName}";
        }

        private async Task GenerateTextAsync()
        {
            ActivityCode branch = await CreateBranchAsync();

            await RefreshSelectionAsync(branch);

            if (!IsAutoGenerateLoop)
            {
                Info = $"Generated {branch.CodeConcatName}";
                return;
            }
            ;

            ActivityCode firstLeaf = await CreateFirstLeafAsync();

            await RefreshSelectionAsync(firstLeaf);

            Info = $"Generated {firstLeaf.CodeConcatName}";
        }

        private async Task<ActivityCode> CreateBranchAsync()
        {
            return await CreateActivityCodeAsync(
                parentObjectId: SelectedActivityCodeNode.Parent.Code.ObjectId.Value,
                codeValue: UserEnteredValue.Trim(),
                description: BuildBranchDescription()
                );
        }

        private async Task<ActivityCode> CreateFirstLeafAsync()
        {

            string description = BuildDescription("1");

            return await CreateActivityCodeAsync(

                parentObjectId:
                    SelectedActivityCode.ObjectId.Value,

                codeValue:
                    "1",

                description:
                    description);
        }

        private async Task<ActivityCode> CreateActivityCodeAsync(int parentObjectId, string codeValue, string description)
        {
            ActivityCode newCode =
                new ActivityCode
                {
                    ParentObjectId = parentObjectId,
                    CodeTypeObjectId = SelectedActivityCode.CodeTypeObjectId,
                    CodeValue = codeValue,
                    Description = description
                };

            var result = await _p6ApiService.Client.CreateActivityCodeAsync(null, new[] { newCode });

            string objectId = result.FirstOrDefault();

            if (String.IsNullOrWhiteSpace(objectId))
            {
                throw new Exception("Unable to create Activity Code.");
            }

            newCode.ObjectId = int.Parse(objectId);

            return newCode;
        }

        private async Task RefreshSelectionAsync(ActivityCode actCode)
        {
            var pickerVM = new ActivityCodePickerViewModel(
                 new ActivityCodePickerModel(_pluginInstance, IsAutoGenerate, ElementIdActivityCodeType)
             );
            await pickerVM.AsyncInit(project: Project, types: new() { ElementIdActivityCodeType });

            SelectedActivityCodeNode = pickerVM.GetNodeByActivityCode(actCode);

            SelectedActivityCode = SelectedActivityCodeNode.Code;

            OnPropertyChanged(string.Empty);
        }

        private bool AutoGenerateCanExecute()
        {
            if (!IsAutoGenerate)
                return false;

            if (!ValidateSelection())
                return false;

            if (!ValidateDescription())
                return false;

            if (IsNumericSelection)
                return ValidateNumericGeneration();

            return ValidateTextGeneration();
        }

        private bool ValidateSelection()
        {
            if (SelectedActivityCode == null)
            {
                Info = "Select Activity Code.";
                return false;
            }

            if (SelectedActivityCodeNode == null)
            {
                Info = "Activity Code tree is unavailable.";
                return false;
            }

            return true;
        }

        private bool ValidateDescription()
        {
            if (String.IsNullOrWhiteSpace(UserEnteredDescription))
            {
                Info = "Enter description.";
                return false;
            }

            return true;
        }

        private bool ValidateNumericGeneration()
        {
            if (!int.TryParse(
                SelectedActivityCode.CodeValue,
                out _))
            {
                Info = "Selected code is not numeric.";
                return false;
            }

            return true;
        }

        private bool ValidateTextGeneration()
        {
            if (!ValidateBranchValue())
                return false;

            if (!ValidateDuplicateBranch())
                return false;

            return true;
        }

        private bool ValidateBranchValue()
        {
            string value =
                UserEnteredValue?.Trim();

            if (String.IsNullOrWhiteSpace(value))
            {
                Info = "Enter branch value.";
                return false;
            }

            if (value.Contains(" "))
            {
                Info = "Spaces are not allowed.";
                return false;
            }

            if (int.TryParse(value, out _))
            {
                Info = "Branch value cannot be numeric.";
                return false;
            }

            return true;
        }

        private bool ValidateDuplicateBranch()
        {
            if (SelectedActivityCodeNode.Parent == null)
                return true;

            bool duplicate =
                SelectedActivityCodeNode
                    .Parent
                    .Children
                    .Any(x =>
                        x != SelectedActivityCodeNode &&
                        x.Code.CodeValue.Equals(
                            UserEnteredValue.Trim(),
                            StringComparison.OrdinalIgnoreCase));

            if (duplicate)
            {
                Info = "Sibling branch already exists.";
                return false;
            }

            return true;
        }

        private bool CanGenerateFirstLeaf()
        {
            if (!ShowGenerateFirstLeafButton)
                return false;

            return ValidateDescription();
        }

        private string BuildDescription(string index)
        {
            return UserEnteredDescription.Replace("{index}", index);
        }

        private string BuildBranchDescription()
        {
            return UserEnteredDescription.Replace("{index}", "").Trim();
        }

        private int GetNextNumericValue()
        {
            var currentCodesIntegerList = SelectedActivityCodeNode.Parent.Children
                .Cast<ActivityCodePickerNodeViewModel>()
                .Select(node => int.TryParse(node.Code.CodeValue, out int parseResult) ? parseResult : 0)
                .ToList();

            var currentMaxValue = currentCodesIntegerList.Max();

            return currentMaxValue + 1;
        }

        private void RefreshUi()
        {
            OnPropertyChanged(nameof(IsNumericSelection));
            OnPropertyChanged(nameof(IsTextSelection));
            OnPropertyChanged(nameof(NextNumericValue));
            OnPropertyChanged(nameof(CanEditValue));
            OnPropertyChanged(nameof(CanEditDescription));
            OnPropertyChanged(nameof(ShowGenerateFirstLeafButton));

            CommandManager.InvalidateRequerySuggested();
        }

        public void EnterAutoGenerateLoop()
        {
            IsAutoGenerateLoop = true;
            _isBranchLocked = true;

            RefreshUi();
        }

        public void ExitAutoGenerateLoop()
        {
            IsAutoGenerateLoop = false;
            _isBranchLocked = false;

            RefreshUi();
        }

        private void UpdateUserEnteredValue()
        {
            if (SelectedActivityCode == null)
            {
                UserEnteredValue = string.Empty;
                return;
            }

            if (IsNumericSelection)
            {
                UserEnteredValue = GetNextNumericValue().ToString();
            }
            // Text selection:
            // Don't overwrite UserEnteredValue.
            // Let the user keep typing/editing the branch value.
        }

    }

}