using System.Collections.ObjectModel;
using System.Threading.Tasks;
using Autocad_Primavera_P6_Plugin.Services.P6ApiService;
using Autodesk.AutoCAD.ApplicationServices;
using App = Autodesk.AutoCAD.ApplicationServices.Application;
using Document = Autodesk.AutoCAD.ApplicationServices.Document;

using Autodesk.AutoCAD.DatabaseServices;
using System;
using System.IO;

namespace Autocad_Primavera_P6_Plugin.UserInterface.UI_InsertBlocksWindowView
{
    public enum BlockTypeMode
    {
        Predefined,
        SelectFromDrawing
    }

    public sealed class PredefinedBlockInfo
    {
        public string Name { get; set; }
        public string FilePath { get; set; }

        public override string ToString()
        {
            return Name;
        }
    }

    public sealed class ActivityCodeSectionModel
    {
        public string ActivtyCodeTypeName = "Boundary Code";
        public string SelectedCodeValue { get; set; }
        public string SelectedCodePath { get; set; }
        public string SelectedCodeValueId { get; set; }
        public string AutoGeneratedCodeValue { get; set; }
        public string AutoGeneratedCodePath { get; set; }
        public string AutoGeneratedCodeValueId { get; set; }
        public string Info { get; set; }
        public bool IsAutoGenerate { get; set; }
    }

    public sealed class InsertBlocksWindowModel
    {
        public MyPlugin PluginInstance = null;
        public BlockReference PreselectedBlock = null;
        public P6ApiService P6ApiService => PluginInstance.MyP6ApiService;

        public Document AcadDoc = null;
        public Project CurrentProject = null;
        public string DefaultBlocksFolder => GetDefaultBlocksFolder();

        public string MoveInfoXPropertyName = "MoveInfo X";
        public string MoveInfoYPropertyName = "MoveInfo Y";

        public ObservableCollection<PredefinedBlockInfo> AvailableBlocks { get; private set; }

        public InsertBlocksWindowModel()
        {
            AvailableBlocks = new ObservableCollection<PredefinedBlockInfo>();
        }

        public void Init()
        {
            // Load Document
            AcadDoc = App.DocumentManager.MdiActiveDocument;
            // Load Project
            CurrentProject = P6ApiService.GetP6ProjectFromDWGFile(AcadDoc);
        }

        private string GetDefaultBlocksFolder()
        {
            string appData = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
            return Path.Combine(appData, "Autocad_Primavera_P6_Plugin", "Blocks");
        }
    }

    internal sealed class BlockSourceResult
    {
        public ObjectId BlockDefinitionId { get; set; }
        public string BlockName { get; set; }
    }
}
