using System.Collections.ObjectModel;
using Autodesk.AutoCAD.DatabaseServices;

namespace Autocad_Primavera_P6_Plugin.UserInterface.UI_InsertBlocksWindowView
{
    public enum BlockTypeMode
    {
        Predefined,
        SelectFromDrawing,
        CopyBlock
    }

    public sealed class PredefinedBlockInfo
    {
        public string Name { get; set; }
        public string FilePath { get; set; }

        public override string ToString()
        {
            return Name;
        }
    }

    public sealed class ActivityCodeSectionModel
    {
        public string SelectedCodeValue { get; set; }
        public string SelectedCodePath { get; set; }
        public string SelectedCodeValueId { get; set; }
        public string AutoGeneratedCodeValue { get; set; }
        public string AutoGeneratedCodePath { get; set; }
        public string AutoGeneratedCodeValueId { get; set; }
        public string Info { get; set; }
        public bool IsAutoGenerate { get; set; }
    }

    public sealed class InsertBlocksWindowModel
    {
        public ObservableCollection<PredefinedBlockInfo> AvailableBlocks { get; private set; }

        public InsertBlocksWindowModel()
        {
            AvailableBlocks = new ObservableCollection<PredefinedBlockInfo>();
        }
    }

    internal sealed class BlockSourceResult
    {
        public ObjectId BlockDefinitionId { get; set; }
        public string BlockName { get; set; }
    }
}
