using System.Collections.ObjectModel;
using System.Threading.Tasks;
using Autocad_Primavera_P6_Plugin.Services.P6ApiService;
using Autodesk.AutoCAD.ApplicationServices;
using AcadApp = Autodesk.AutoCAD.ApplicationServices.Application;
using Document = Autodesk.AutoCAD.ApplicationServices.Document;

using Autodesk.AutoCAD.DatabaseServices;
using System;
using System.IO;
using Autocad_Primavera_P6_Plugin.Services.AutocadService;
using System.Linq;

namespace Autocad_Primavera_P6_Plugin.UserInterface.UI_InsertBlocksWindowView
{
    public enum BlockTypeMode
    {
        Predefined,
        SelectFromDrawing
    }

    internal sealed class BlockSourceResult
    {
        public ObjectId BlockDefinitionId { get; set; }
        public string BlockName { get; set; }
    }

    public sealed class PredefinedBlockInfo
    {
        public string Name { get; set; }
        public string FilePath { get; set; }

        public override string ToString()
        {
            return Name;
        }
    }

    public sealed class ActivityCodeSectionModel
    {
        public string ActivtyCodeTypeName = "Boundary Code";
        public string SelectedCodeValue { get; set; }
        public string SelectedCodePath { get; set; }
        public string SelectedCodeValueId { get; set; }
        public string AutoGeneratedCodeValue { get; set; }
        public string AutoGeneratedCodePath { get; set; }
        public string AutoGeneratedCodeValueId { get; set; }
        public string Info { get; set; }
        public bool IsAutoGenerate { get; set; }
    }

    public sealed class InsertBlocksWindowModel
    {
        public MyPlugin PluginInstance = null;
        public P6ApiService MyP6ApiService => PluginInstance.MyP6ApiService;
        public AutocadService MyAutocadService => PluginInstance.MyAutocadService;

        public Document ActAcadDoc = null;
        public Project CurrentProject = null;
        public PlugInBlockReference PreselectedBlock = null;

        // ----- FUTURE REMOVE : STRAT -----
        public string DefaultBlocksFolder => GetDefaultBlocksFolder();

        private string GetDefaultBlocksFolder()
        {
            string appData = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
            return Path.Combine(appData, "Autocad_Primavera_P6_Plugin", "Blocks");
        }

        public string MoveInfoXPropertyName = "MoveInfo X";
        public string MoveInfoYPropertyName = "MoveInfo Y";

        public ObservableCollection<PredefinedBlockInfo> AvailableBlocks { get; private set; } = new ObservableCollection<PredefinedBlockInfo>();
        // ----- FUTURE REMOVE : END   -----

        public void Init()
        {
            SetActiveAutocadDocument();
            SetCurrentP6Project();
            SetImpliedSelectedBlock();
        }

        private void SetActiveAutocadDocument()
        {
            ActAcadDoc = AcadApp.DocumentManager.MdiActiveDocument;
        }

        private void SetCurrentP6Project()
        {
            CurrentProject = MyP6ApiService.GetP6ProjectFromDWGFile(ActAcadDoc);
        }

        private void SetImpliedSelectedBlock()
        {
            var _selectedBlocks = MyAutocadService.GetPluginBlockImpliedSelected(ActAcadDoc);
            var _selectedBlock = _selectedBlocks.Count > 0 ? _selectedBlocks.Last() : null;

            if (_selectedBlock != null)
            {
                PreselectedBlock = new PlugInBlockReference(ActAcadDoc, _selectedBlock);
            };
        }

    }

}
